# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.16-SNAPSHOT
# Mod Properties
mod_version=1.9.5
maven_group=semmiedev
archives_base_name=disc_jockey
# Dependencies
fabric_api_version=0.160.5+26.3
